apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
data:
  mysql-root-password: c2FpYjEyMw==    # base64 encoded value of 'zaib123'
  mysql-password: ZGV2X3Bhc3N3b3Jk     # base64 encoded value of 'dev_password'
  nextcloud-admin-password: c3VraGVyYTc1OTU=  # base64 encoded value of 'sukhera7595'

