apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082  # Specify a node port here
  selector:
    app: nextcloud

